nameOverride: "hello-world-production"
replicaCount: 3

image:
  repository: 675327529402.dkr.ecr.ap-southeast-1.amazonaws.com/fast-campus
  pullPolicy: IfNotPresent
  tag: ""

service: 
  targetPort: 5000

resources: 
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi